
service: aws-nodejs

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3
  #region: eu-west-1

functions:
  audio:
    handler: api/events.audio
    events:
      - http:
          path: api/events
          method: get
          cors: true


