#API SERVERLESS FILE

#version pinned to ensure all use same version of framework.
#frameworkVersion: "=1.5"

service: GunShotDetectionSystemDev001

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1


functions:
  Incidents:
    handler: api/Incidents.incidents
    events:
      - http:
          integration: lambda
          path: api/Incidents
          method: get
          cors: true
  ModuleStatus:
    handler: api//Modules.GetModuleStatus
    events:
      - http:
          integration: lambda
          path: api/ModuleStatus
          method: get
          cors: true
          request:
            template:
              application/json: >
               {
                 "foo" : "$input.params('foo')",
                 "someData": "$input.params('some_data')"
               }
  ModuleStatusWithID:
    handler: api//Modules.GetModuleStatus
    events:
      - http:
          path: api/ModuleStatus/{moduleId}
          method: get
          cors: true
  ModuleError:
    handler: api/Modules.PostModuleError
    events:
      - http:
          integration: lambda
          path: api/ModuleError
          method: post
          cors: true