#API SERVERLESS FILE

#version pinned to ensure all use same version of framework.
#frameworkVersion: "=1.5"

service: GunShotDetectionSystemDev008

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1

functions:
  ModuleStatusWithId:
    handler: api/Modules.GetModuleStatus
    events:
      - http:
          path: api/ModuleStatus/{moduleId}
          integration: lambda
          method: get
          cors: true
  ModuleStatus:
    handler: api/Modules.GetModuleStatus
    events:
      - http:
          path: api/ModuleStatus
          integration: lambda
          method: get
          cors: true