#API SERVERLESS FILE

#version pinned to ensure all use same version of framework.
#frameworkVersion: "=1.5"

service: GunShotDetectionSystemDev001

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1


functions:
  Incidents:
    handler: api/Incidents.incidents
    events:
      - http:
          path: api/Incidents
          method: get
          cors: true