
service: aws-nodejs

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

functions:
  detectorstatus:
        handler: api/DetectorStatus.detectorstatus
        events:
          - http:
              path: api/DetectorStatus
              method: get
              cors: true
  incidents:
      handler: api/Incidents.incidents
      events:
        - http:
            path: api/Incidents
            method: get
            cors: true
  incident:
      handler: api/Incident.incident
      events:
        - http:
            path: api/Incident
            method: get
            cors: true
  eventList:
      handler: api/EventList.eventList
      events:
        - http:
            path: api/EventList
            method: get
            cors: true
  cameraPanel:
    handler: api/CameraPanel.cameraPanel
    events:
        - http:
            path: api/CameraList
            method: get
            cors: true
    playList:
      handler: api/PlaybackList.playbacklist
      events:
          - http:
              path: api/PlaybackList
              method: get
              cors: true